CREATE DATABASE IF NOT EXISTS note_app;
USE note_app;
CREATE TABLE USERS(
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    contact VARCHAR(20);
    password VARCHAR(255) NOT NULL,
    profile_image VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS notes (
    note_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    note TEXT NOT NULL,
    date DATE,FOREIGN KEY (user_id) REFERENCES users(id);
);
